line-length = 100
target-version = "py39"

[lint]
select = ["E", "F", "I", "B", "UP", "S"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
skip-magic-trailing-comma = false
