name: CI

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Lint (ruff)
        run: ruff check . && ruff format --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Test (pytest)
        run: pytest --cov --cov-report=xml
